// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjXRU8C73qzWfkGYFl6uyHIRi_-x6wzV0',
    appId: '1:1066185787341:web:1994241817e6977cc6e684',
    messagingSenderId: '1066185787341',
    projectId: 'box-cricket-72b9b',
    authDomain: 'box-cricket-72b9b.firebaseapp.com',
    storageBucket: 'box-cricket-72b9b.firebasestorage.app',
    measurementId: 'G-NPQYD0QBC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vq6_EoD8EzY6_PujjtZEG_3VCSbC78Q',
    appId: '1:1066185787341:android:3cf1bfba87aa6c3fc6e684',
    messagingSenderId: '1066185787341',
    projectId: 'box-cricket-72b9b',
    storageBucket: 'box-cricket-72b9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPcP9A64rJnenha0LRq7vEOIzS9PISFwU',
    appId: '1:1066185787341:ios:18fe9dd46625b6c4c6e684',
    messagingSenderId: '1066185787341',
    projectId: 'box-cricket-72b9b',
    storageBucket: 'box-cricket-72b9b.firebasestorage.app',
    iosBundleId: 'com.example.boxCricketNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPcP9A64rJnenha0LRq7vEOIzS9PISFwU',
    appId: '1:1066185787341:ios:18fe9dd46625b6c4c6e684',
    messagingSenderId: '1066185787341',
    projectId: 'box-cricket-72b9b',
    storageBucket: 'box-cricket-72b9b.firebasestorage.app',
    iosBundleId: 'com.example.boxCricketNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjXRU8C73qzWfkGYFl6uyHIRi_-x6wzV0',
    appId: '1:1066185787341:web:60092640ee0cce71c6e684',
    messagingSenderId: '1066185787341',
    projectId: 'box-cricket-72b9b',
    authDomain: 'box-cricket-72b9b.firebaseapp.com',
    storageBucket: 'box-cricket-72b9b.firebasestorage.app',
    measurementId: 'G-GZ38S7Y43V',
  );
}
