// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjKWwKmWf92JthQ9fDpRhuB8GkkCtC10',
    appId: '1:6843481967:web:7f4f138d8d348cc2cc729a',
    messagingSenderId: '6843481967',
    projectId: 'box-cricket-df427',
    authDomain: 'box-cricket-df427.firebaseapp.com',
    storageBucket: 'box-cricket-df427.firebasestorage.app',
    measurementId: 'G-8VJ4QHKD63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD1eiwwO6WNgjTYA59Es99r6ncQgIpvXQ',
    appId: '1:6843481967:android:41ae8c8722c3e868cc729a',
    messagingSenderId: '6843481967',
    projectId: 'box-cricket-df427',
    storageBucket: 'box-cricket-df427.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPd4ZimKi0RtzJmlHULjkMdNP1VuyqEk',
    appId: '1:6843481967:ios:70940802eee7ed00cc729a',
    messagingSenderId: '6843481967',
    projectId: 'box-cricket-df427',
    storageBucket: 'box-cricket-df427.firebasestorage.app',
    iosBundleId: 'com.boxcricket.turfproOwner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPd4ZimKi0RtzJmlHULjkMdNP1VuyqEk',
    appId: '1:6843481967:ios:70940802eee7ed00cc729a',
    messagingSenderId: '6843481967',
    projectId: 'box-cricket-df427',
    storageBucket: 'box-cricket-df427.firebasestorage.app',
    iosBundleId: 'com.boxcricket.turfproOwner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgKW_q7BeK8ph0hsJ90-gz9URU4TXfcIE',
    appId: '1:6843481967:web:6014b5102d1244f6cc729a',
    messagingSenderId: '6843481967',
    projectId: 'box-cricket-df427',
    authDomain: 'box-cricket-df427.firebaseapp.com',
    storageBucket: 'box-cricket-df427.firebasestorage.app',
    measurementId: 'G-L5DWMRGE6M',
  );

}